### ISSUE TITLE
Retours sur l'utilisation de l'outil 

### ISSUE THREAD

**Issue by mathildehg** [taniki/playlists#7]
Propositions d'amélioration de l'outil 

**1. visite d'une page** 
- lorsque l'on clique sur une carte, ouvrir la page dans un nouvel onglet, afin de pouvoir rester sur la page de la playlist 
- proposer un bouton partager ? 

**2.  Edition**  
- possibilité de copier/coller l'URL d'un jeu de données dans le moteur de recherche 
- la suppression d'un jeu de données de la playlist lorsque l'on clique sur une carte n'est pas très intuitive. Proposer une croix dans le coin de la carte ? 
- proposer un bouton "enregistrer" plutôt que "sortir de l'édition"
- quid de proposer des catégories dans les playlists ? Exemple: dans une playlist relative aux données de l'économie circulaire, avoir la possibilité d'organiser la playlist en plusieurs catégories : offre, consommation, recyclage, etc.

**Comment by taniki** [comment]
- [x] ouvrir un nouvel onglet https://github.com/taniki/playlists/commit/a480b51cdaea58abe89c8bcaa857cb12ba3879bc
- [ ] bouton partager
- [ ] ajouter la résolution par url
- [ ] rajouter une indication sur les interactions (double clic pour supprimer ou ajouter un jeu de données)

- :x: sous-section dans une playlist : dans un premier temps, on va garder le truc simple en organisant les catégories en plusieurs playlists

**Comment by mathildehg** [comment]
@taniki  as-tu pu avancer sur le point "résolution par url" ? Cela me ferait gagner du temps, par exemple pour la playlist datafin :)

**Comment by taniki** [comment]
@mathildehg j'essaie de te faire ça d'ici demain (:

**Comment by taniki** [comment]
@mathildehg c'est bon pour l'ajout par url e1f45b6482214c54a5d96625dbe19eecd7efcb5b

**Comment by taniki** [comment]
22705d82b3c1bef380d05278bf4d1e53bbc1858e

**Comment by mathildehg** [comment]
Top merci @taniki !
