### ISSUE TITLE
Page d'accueil sans être loggué : erreurs JS

### ISSUE THREAD

**Issue by abulte** [taniki/playlists#8]
La page d'accueil renvoie pleins d'erreur JS. J'ai l'impression que le statut loggué n'ait pas pris en compte et que l'outil essaie d'accéder à l'API de data.gouv.fr sans être identifié.

<img width="458" alt="Capture d'écran 2019-12-12 16 32 03" src="https://user-images.githubusercontent.com/119625/70725667-1a31db00-1cfd-11ea-9a43-e779718900c3.png">

**Comment by taniki** [comment]
bug quand le token est pas frais. l'usager est maintenant déloggué dans ce cas
